
import { UpgradeBlueprint } from './ai.service';

// ARCHITECTURE BLUEPRINT V7.2
// This file defines the catalog of unlockable, high-impact neural upgrades.
// Each blueprint is a manifest for a feature that can be dynamically integrated
// by the NeuralOrchestratorService.

export const NEURAL_UPGRADE_BLUEPRINTS: UpgradeBlueprint[] = [
  // -- Foundational Upgrades --
  {
    id: 'upg-holographic-mixer',
    title: 'Holographic Mixing Console',
    type: 'Software',
    description: 'Visualize and manipulate your mix in a 3D holographic interface. Spatially position tracks, create dynamic automation planes, and manage signal flow with unprecedented clarity.',
    cost: '$149',
    impact: 'Transformative',
    rationale: 'Traditional 2D mixers are a cognitive bottleneck. A holographic representation maps directly to human spatial intuition, enabling faster, more accurate mix decisions.',
    targetArea: 'Mixing',
    priority: 'High',
    prerequisites: ['Minimum 3 active tracks in a project', 'Basic understanding of signal routing'],
    actionLabel: 'Activate Holo-Mixer',
    toolId: 'mixer',
    outcomeMetric: { label: 'Spatial Clarity', value: '+80%' },
    preferredViews: ['mixer', 'studio'],
    rank: ({ context }) => 85 + (context.trackCount > 5 ? 10 : 0),
  },
  {
    id: 'upg-quantum-drum-engine',
    title: 'Quantum Drum Engine',
    type: 'Software',
    description: 'A generative rhythm engine that uses quantum probability models to create novel, complex, and evolving drum patterns beyond the limitations of traditional sequencing.',
    cost: '$99',
    impact: 'High',
    rationale: 'Human-programmed rhythms are often predictable. The Quantum Engine explores the latent space of rhythmic possibility to generate grooves that feel both complex and organic.',
    targetArea: 'Rhythm',
    priority: 'High',
    prerequisites: ['Drum Machine V6 Installed', 'Familiarity with step sequencing'],
    actionLabel: 'Install Quantum Engine',
    toolId: 'drum-machine',
    outcomeMetric: { label: 'Rhythmic Complexity', value: '+95%' },
    preferredViews: ['drum-machine', 'studio'],
    rank: ({ profile }) => profile.daw.includes('Drum Machine V6') ? 92 : 20,
  },
  {
    id: 'upg-precog-mastering-ai',
    title: 'Precognitive Mastering AI',
    type: 'Cloud Service',
    description: 'An AI mastering suite that analyzes your track and references millions of commercially successful records to predict the optimal mastering chain for your specific genre and target platform.',
    cost: '$199',
    impact: 'Critical',
    rationale: 'Mastering is the final, crucial step. This AI removes guesswork, providing a competitive, release-ready master in minutes, not hours.',
    targetArea: 'Mastering',
    priority: 'Critical',
    prerequisites: ['A completed track (minimum 2 minutes)', 'Target genre selected'],
    actionLabel: 'Engage Precognitive AI',
    toolId: 'mastering',
    outcomeMetric: { label: 'Commercial Viability', value: '+75%' },
    preferredViews: ['mastering', 'studio'],
    rank: ({ context }) => context.releaseReadyCount > 0 ? 98 : 70,
  },

  // -- Advanced Production & Performance Upgrades --
  {
    id: 'upg-neural-stem-splitter',
    title: 'Neural Stem Splitter',
    type: 'Software',
    description: 'Real-time, high-fidelity source separation. Isolate vocals, drums, bass, and instruments from any stereo track for remixing, sampling, or practice.',
    cost: '$79',
    impact: 'High',
    rationale: 'Unlocking the components of existing audio is a creative superpower. This tool turns any song into a palette of new material.',
    targetArea: 'Sampling & Remixing',
    priority: 'Medium',
    prerequisites: ['DJ Deck V5 interface'],
    actionLabel: 'Unlock Stem Splitter',
    toolId: 'dj-deck',
    outcomeMetric: { label: 'Creative Options', value: '+120%' },
    preferredViews: ['dj-deck', 'practice'],
    rank: ({ viewMode }) => viewMode === 'dj-deck' ? 90 : 65,
  },
  {
    id: 'upg-arranger-ai-co-pilot',
    title: 'Arrangement Co-Pilot',
    type: 'Cloud Service',
    description: 'An AI partner that analyzes your loop or pattern and suggests full song structures, transitions, and dynamic variations to help you break out of the 8-bar loop.',
    cost: '$129',
    impact: 'High',
    rationale: 'Finishing tracks is hard. The Co-Pilot provides a structural scaffold, helping you build a complete arrangement from a single idea.',
    targetArea: 'Arrangement',
    priority: 'High',
    prerequisites: ['A defined 4-8 bar loop'],
    actionLabel: 'Activate Co-Pilot',
    toolId: 'studio',
    outcomeMetric: { label: 'Track Completion Rate', value: '+60%' },
    preferredViews: ['studio', 'piano-roll'],
    rank: ({ context }) => context.activeLoopBars >= 4 ? 95 : 50,
  },
   {
    id: 'upg-vocal-synth-pro',
    title: 'Vocal Synth Pro',
    type: 'Software',
    description: 'A professional vocal synthesis and correction suite. Design realistic vocal lines from text, apply deep-fake style voice modeling, and perform surgical pitch and time correction.',
    cost: '$249',
    impact: 'Transformative',
    rationale: 'Professional vocals are often the missing link. This suite provides a complete, in-the-box solution for creating and perfecting release-quality vocal tracks.',
    targetArea: 'Vocals',
    priority: 'Critical',
    prerequisites: ['Microphone connected', 'Understanding of basic vocal mixing'],
    actionLabel: 'Install Vocal Synth Pro',
    toolId: 'vocal-suite',
    outcomeMetric: { label: 'Vocal Professionalism', value: '+90%' },
    preferredViews: ['vocal-suite', 'studio'],
    rank: ({ profile }) => profile.hasMicrophone ? 94 : 60,
  },
];
