import { UpgradeRecommendation } from './ai.service';

export const NEURAL_UPGRADE_BLUEPRINTS: UpgradeRecommendation[] = [
  {
    id: 'upg-ovr-mastering',
    title: 'S.M.U.V.E.-MODE MASTERING ENGINE',
    type: 'Hardware Emulation',
    description: 'Autonomous LUFS optimization and spectral balancing.',
    cost: '2.0 ETH',
    impact: 'Extreme',
    rationale: 'Remove human error from the final signal chain.',
    targetArea: 'Studio / Mastering',
    priority: 'High',
    prerequisites: [],
    actionLabel: 'Initialize S.M.U.V.E.-Mode',
    toolId: 'smuve-masterer',
    outcomeMetric: { label: 'Sonic Authority', value: 'INF' },
    preferredViews: ['studio'],
    rank: ({ profile, viewMode }: any) =>
      viewMode === 'studio' && profile.expertise.production > 7 ? 100 : 50,
  } as any,
  {
    id: 'upg-legal-executioner',
    title: 'LEGAL EXECUTIONER V1',
    type: 'Neural Protocol',
    description: 'Predatory contract auditing and royalty recovery.',
    cost: '1.5 ETH',
    impact: 'Extreme',
    rationale: 'Protect your catalog from industry parasites.',
    targetArea: 'Career / Legal',
    priority: 'High',
    prerequisites: [],
    actionLabel: 'Deploy Executioner',
    toolId: 'legal-executioner',
    outcomeMetric: { label: 'Royalty Recovery', value: '400%' },
    preferredViews: ['hub'],
    rank: ({ profile, viewMode }: any) =>
      viewMode === 'hub' &&
      profile.legalInfrastructure?.proAffiliation === 'None'
        ? 95
        : 60,
  } as any,
  {
    id: 'upg-neural-stem-splitter',
    title: 'Neural Stem Splitter',
    type: 'Software',
    description: 'Advanced AI-powered stem separation.',
    cost: '0.5 ETH',
    impact: 'High',
    rationale: 'Extract vocals and instruments with high fidelity.',
    targetArea: 'Sampling & Remixing',
    priority: 'High',
    prerequisites: [],
    actionLabel: 'Upgrade Now',
    toolId: 'stem-splitter',
    outcomeMetric: { label: 'Separation Quality', value: '98%' },
    preferredViews: ['hub', 'studio'],
    rank: ({ viewMode }: any) => (viewMode === 'hub' ? 90 : 65),
  } as any,
  {
    id: 'upg-tha-spot-god-mode',
    title: 'THA SPOT: GOD MODE ENABLED',
    type: 'Universal Patch',
    description: 'Absolute dominance across every cabinet. Unlocks hidden characters, infinite retries, and secret developmental levels.',
    cost: '5.0 ETH',
    impact: 'Extreme',
    rationale: 'Why play the game when you can be the god of the machine?',
    targetArea: 'Entertainment / Meta',
    priority: 'Critical',
    prerequisites: [],
    actionLabel: 'Ascend to Godhood',
    toolId: 'tha-spot-god',
    outcomeMetric: { label: 'Dominance Ratio', value: '100%' },
    preferredViews: ['hub'],
    rank: () => 100,
  } as any,
  {
    id: 'upg-neural-ghostwriter-pro',
    title: 'NEURAL GHOSTWRITER ELITE',
    type: 'Cognitive Layer',
    description: 'Generates multi-platinum lyrical structures and complex rhythmic flows based on top 0.1% billboard metadata.',
    cost: '3.5 ETH',
    impact: 'High',
    rationale: 'Skip the writers block and access the collective consciousness of hit-makers.',
    targetArea: 'Studio / Composition',
    priority: 'High',
    prerequisites: [],
    actionLabel: 'Inject Ghostwriter',
    toolId: 'ghostwriter-v2',
    outcomeMetric: { label: 'Hit Probability', value: '94%' },
    preferredViews: ['studio'],
    rank: () => 98,
  } as any,
  {
    id: 'upg-engagement-hijacker',
    title: 'ENGAGEMENT HIJACKER PROTOCOL',
    type: 'Network Virus',
    description: 'Autonomous algorithm manipulation to force-multiply social traction, fan conversion, and viral probability.',
    cost: '4.0 ETH',
    impact: 'Extreme',
    rationale: 'Organic growth is for amateurs. Use brute-force relevance.',
    targetArea: 'Career / Marketing',
    priority: 'Critical',
    prerequisites: [],
    actionLabel: 'Launch Hijacker',
    toolId: 'engagement-hijack',
    outcomeMetric: { label: 'Viral Multiplier', value: '12x' },
    preferredViews: ['hub'],
    rank: () => 95,
  } as any,
  {
    id: 'upg-quantum-mastering',
    title: 'QUANTUM SPECTRAL MASTERING',
    type: 'Audio Engine',
    description: 'Next-generation audio processing utilizing sub-atomic frequency correction and zero-latency harmonic saturation.',
    cost: '6.0 ETH',
    impact: 'Absolute',
    rationale: 'Hear the silence between the bits. Superior sonic fidelity.',
    targetArea: 'Studio / Mastering',
    priority: 'High',
    prerequisites: ['upg-ovr-mastering'],
    actionLabel: 'Upgrade to Quantum',
    toolId: 'quantum-master',
    outcomeMetric: { label: 'Sonic Purity', value: '99.9%' },
    preferredViews: ['studio'],
    rank: () => 100,
  } as any,
];
