import { ThaSpotFeed } from './game';

export const THA_SPOT_FALLBACK_FEED: ThaSpotFeed = {
  badges: [
    { id: 'featured', label: 'Featured', tone: 'primary' },
    { id: 'trending', label: 'Trending', tone: 'secondary' },
    { id: 'staff-pick', label: 'Staff Pick', tone: 'accent' },
    { id: 'new-drop', label: 'New Drop', tone: 'warning' },
    { id: 'tournament-live', label: 'Tournament Live', tone: 'secondary' },
  ],
  rooms: [
    {
      id: 'all',
      name: 'All Games',
      icon: 'grid_view',
      description: 'Fallback arcade roster while the live feed reconnects.',
    },
    {
      id: 'arcade',
      name: 'Arcade',
      icon: 'joystick',
      description: 'Fast starts, quick resets, and reactive cabinet runs.',
      rules: { tags: ['Arcade', 'Reflex'] },
    },
    {
      id: 'strategy',
      name: 'Strategy',
      icon: 'psychology',
      description: 'Puzzle and board-first play tuned for thinkers.',
      rules: { genres: ['Strategy', 'Puzzle', 'Classic'] },
    },
  ],
  liveEvents: [
    {
      id: 'fallback-showdown',
      title: 'Fallback Floor Challenge',
      description: 'Queue up while Tha Spot refreshes the live schedule.',
      roomId: 'arcade',
      reward: 'Featured cosmetic',
      reward: 'Studio skin drop',
      status: 'live',
      windowLabel: 'Live now',
      badgeId: 'tournament-live',
      featuredGameId: '1',
      schedule: {
        startAt: '2026-04-01T18:00:00.000Z',
        endAt: '2026-04-30T23:59:59.000Z',
        recurrence: 'once',
        rewardType: 'cosmetic',
      },
    },
  ],
  socialPresence: [
    {
      id: 'fallback-1',
      name: 'StudioGhost',
      status: 'hosting',
      activity: 'Hosting a reflex warmup room',
      roomId: 'arcade',
      gameId: '1',
      relationship: 'friend',
      joinable: true,
      cta: 'Join friend',
    },
    {
      id: 'fallback-2',
      name: 'ExecutiveGrid',
      status: 'invited',
      activity: 'Party invite waiting in Grandmaster Chess',
      roomId: 'strategy',
      gameId: '3',
      relationship: 'invite',
      pendingInvite: true,
      partySize: 2,
      cta: 'Accept invite',
      alert: 'Invite expires soon.',
    },
  ],
  promotions: [
    {
      id: 'promo-studio',
      title: 'Jump back into Studio',
      description:
        'Carry the energy from Tha Spot into a new production session.',
      route: '/studio',
      icon: 'tune',
      cta: 'Open Studio',
      roomIds: ['arcade'],
      audienceTags: ['returning', 'producer'],
      priority: 8,
      campaignType: 'studio',
    },
    {
      id: 'promo-intel',
      title: 'Open the Intel stack',
      description: 'Review live room data and plan your next move.',
      route: '/strategy',
      icon: 'analytics',
      cta: 'Open Intel',
      roomIds: ['strategy'],
      audienceTags: ['competitive'],
      priority: 7,
      campaignType: 'intel',
    },
  ],
  leaderboards: [],
  recommendationRails: [
    {
      id: 'fallback-returning',
      title: 'Warm restart picks',
      subtitle: 'Use your last sessions to snap back into flow.',
      audience: { minPlays: 1, maxPlays: 999 },
      roomIds: ['all'],
      weights: {
        history: 16,
        crowd: 4,
        badge: 3,
        novelty: 1,
        room: 2,
        genre: 6,
      },
      maxItems: 4,
    },
    {
      id: 'fallback-producer',
      title: 'Producer crossover',
      subtitle: 'Rhythm and puzzle cabinets that fit studio downtime.',
      audience: { primaryGenres: ['Hip Hop', 'R&B', 'Pop'] },
      roomIds: ['arcade', 'strategy'],
      weights: {
        genre: 14,
        history: 5,
        crowd: 3,
        badge: 4,
        novelty: 2,
        room: 4,
      },
      maxItems: 4,
    },
  ],
  games: [
    {
      id: '1',
      name: 'Neon Drift X',
      url: '/assets/games/neon-drift/neon-drift.html',
      description: 'Precision traffic runs with instant offline recovery.',
      genre: 'Racing',
      rating: 4.8,
      playersOnline: 420,
      availability: 'Offline',
      tags: ['Arcade', 'Offline', 'Reflex'],
      badgeIds: ['featured'],
      queueEstimateMinutes: 0,
      sessionObjectives: [
        'Survive 90 seconds',
        'Finish a flawless lane swap chain',
      ],
      controlHints: [
        'Arrow keys to weave lanes',
        'Stay centered before boosts',
      ],
      launchConfig: {
        difficulty: 'Medium',
        objectives: ['Survive the first wave', 'Keep a clean run going'],
        controls: ['Arrow keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/neon-drift/neon-drift.html',
        approvedExternalUrl: '/assets/games/neon-drift/neon-drift.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'Offline',
        accentStart: '#38bdf8',
        accentEnd: '#6366f1',
      },
    },
    {
      id: '2',
      name: 'Tempo Lockdown',
      url: '/assets/games/tempo-lockdown/tempo-lockdown.html',
      description: 'A responsive offline rhythm lane for short focus sprints.',
      genre: 'Rhythm',
      rating: 4.8,
      playersOnline: 390,
      availability: 'Offline',
      tags: ['Rhythm', 'Arcade', 'Original'],
      badgeIds: ['staff-pick'],
      queueEstimateMinutes: 0,
      sessionObjectives: ['Hold a clean note chain', 'Stay above 95% timing'],
      sessionObjectives: ['Hold a clean 25-note run', 'Stay above 95% timing'],
      controlHints: ['Use the displayed lane keys', 'Anticipate sync shifts'],
      launchConfig: {
        difficulty: 'Adaptive',
        objectives: ['Keep the meter green', 'Trigger a perfect run'],
        controls: ['Lane keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/tempo-lockdown/tempo-lockdown.html',
        approvedExternalUrl: '/assets/games/tempo-lockdown/tempo-lockdown.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'Offline',
        accentStart: '#34d399',
        accentEnd: '#059669',
      },
    },
    {
      id: '3',
      name: 'Grandmaster Chess',
      url: 'https://poki.com/en/g/master-chess',
      description:
        'Long-form strategy sessions with a steady competitive queue.',
      genre: 'Strategy',
      rating: 4.9,
      playersOnline: 32400,
      availability: 'Online',
      tags: ['Strategy', 'Logic', 'Classic'],
      badgeIds: ['trending'],
      queueEstimateMinutes: 1,
      sessionObjectives: [
        'Win material by move 15',
        'Convert one endgame cleanly',
      ],
      controlHints: [
        'Open the center early',
        'Review checks, captures, threats',
      ],
      launchConfig: {
        difficulty: 'Ranked',
        objectives: ['Hold tempo', 'Finish with a clean conversion'],
        controls: ['Mouse'],
        modes: ['Solo', 'Versus'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://poki.com/en/g/master-chess',
        approvedExternalUrl: 'https://poki.com/en/g/master-chess',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://poki.com'],
      },
      art: {
        eyebrow: 'Strategy',
        accentStart: '#f8fafc',
        accentEnd: '#1e293b',
      },
    },
    {
      id: '4',
      name: 'Cipher Surge',
      url: '/assets/games/cipher-surge/cipher-surge.html',
      description:
        'Offline neural pattern-defense game with polished AI memory rounds and instant retries.',
      genre: 'Puzzle',
      rating: 4.8,
      playersOnline: 510,
      availability: 'Offline',
      tags: ['Puzzle', 'AI', 'Original', 'Logic'],
      badgeIds: ['new-drop', 'staff-pick'],
      queueEstimateMinutes: 0,
      sessionObjectives: [
        'Clear five neural rounds',
        'Finish with at least 70% integrity',
      ],
      controlHints: [
        'Watch the full sequence before reacting',
        'Prioritize rhythm over speed on longer chains',
      ],
      launchConfig: {
        difficulty: 'Adaptive',
        objectives: [
          'Hold integrity above 70%',
          'Perfect one full pattern chain',
        ],
        controls: ['Mouse or touch'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/cipher-surge/cipher-surge.html',
        approvedExternalUrl: '/assets/games/cipher-surge/cipher-surge.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'AI Puzzle',
        accentStart: '#8b5cf6',
        accentEnd: '#4c1d95',
      },
    },
    {
      id: '5',
      name: 'Pac-Man Classic',
      url: 'https://pacman.live/play.html',
      description:
        'High-quality retro cabinet with polished route play and instant arcade readability.',
      genre: 'Classic',
      rating: 4.9,
      playersOnline: 15400,
      availability: 'Online',
      tags: ['Classic', 'Arcade', 'Retro'],
      badgeIds: ['trending'],
      queueEstimateMinutes: 0,
      sessionObjectives: ['Clear two boards', 'Bank one ghost combo'],
      controlHints: [
        'Use corners for ghost control',
        'Commit to power-pellet routes',
      ],
      launchConfig: {
        difficulty: 'Classic',
        objectives: ['Beat your route time', 'Convert a full power cycle'],
        controls: ['Arrow keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://pacman.live/play.html',
        approvedExternalUrl: 'https://pacman.live/play.html',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://pacman.live'],
      },
      art: {
        eyebrow: 'Retro',
        accentStart: '#facc15',
        accentEnd: '#eab308',
      },
    },
  ],
};
