import { Game } from './game';

/**
 * Curated CrazyGames catalog (web-source expansion wave).
 *
 * Every title below was verified playable before inclusion: the provider's
 * /embed/ endpoint answered HTTP 200 with no X-Frame-Options / CSP
 * frame-ancestors blocking, so these play inline inside the cabinet iframe.
 * The same URL serves as the external fallback, mirroring the RetroGames
 * launch contract. CrazyGames is already a trusted cabinet host
 * (games.crazygames.com) — www.crazygames.com/embed/ is the same provider's
 * first-party embedding endpoint.
 *
 * These are modern, widely known, high-quality browser games filling genre
 * gaps the emulation archive cannot serve (browser-native co-op, party,
 * .io PvP, puzzle-platformer co-op, modern endless runners).
 */
export const CURATED_CRAZYGAMES_GAMES: Game[] = [
  {
    id: 'cg-run-3',
    name: 'Run 3',
    url: 'https://www.crazygames.com/embed/run-3',
    description:
      'Iconic endless space runner: gravity flips across tunnel walls, locked characters to unlock, and infinite procedurally stacked levels.',
    genre: 'Action',
    rating: 4.7,
    playersOnline: 31000,
    availability: 'Online',
    tags: ['Action', 'Runner', 'Platformer', 'Multiplayer', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending', 'featured'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/run-3',
      approvedExternalUrl: 'https://www.crazygames.com/embed/run-3',
      embedMode: 'inline',
      controls: ['Keyboard', 'Touch'],
      modes: ['Solo', 'Local Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Web Classic', accentStart: '#22d3ee', accentEnd: '#0e7490' },
  },
  {
    id: 'cg-paper-minecraft',
    name: 'Paper Minecraft',
    url: 'https://www.crazygames.com/embed/paper-minecraft',
    description:
      'The beloved 2D Minecraft sandbox: mine, craft, build, and survive through day-night cycles in creative or survival mode.',
    genre: 'Adventure',
    rating: 4.6,
    playersOnline: 27000,
    availability: 'Online',
    tags: ['Adventure', 'Sandbox', 'Survival', 'Crafting', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'staff-pick'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/paper-minecraft',
      approvedExternalUrl: 'https://www.crazygames.com/embed/paper-minecraft',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Sandbox Icon', accentStart: '#4ade80', accentEnd: '#166534' },
  },
  {
    id: 'cg-fireboy-watergirl',
    name: 'Fireboy and Watergirl',
    url: 'https://www.crazygames.com/embed/fireboy-and-watergirl-the-forest-temple',
    description:
      'The definitive two-player co-op puzzle platformer: guide Fireboy and Watergirl through the Forest Temple using elemental switches, levers, and teamwork.',
    genre: 'Adventure',
    rating: 4.7,
    playersOnline: 22000,
    availability: 'Online',
    tags: ['Adventure', 'Puzzle', 'Platformer', 'Co-op', 'Multiplayer', 'CrazyGames'],
    badgeIds: ['modern', 'featured', 'staff-pick'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl:
        'https://www.crazygames.com/embed/fireboy-and-watergirl-the-forest-temple',
      approvedExternalUrl:
        'https://www.crazygames.com/embed/fireboy-and-watergirl-the-forest-temple',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Co-op', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Co-op Legend', accentStart: '#f87171', accentEnd: '#1d4ed8' },
  },
  {
    id: 'cg-narrow-one',
    name: 'Narrow One',
    url: 'https://www.crazygames.com/embed/narrow-one',
    description:
      'Fast multiplayer archery capture-the-flag: bow duels, vertical castle maps, and real-time team showdowns in a vivid stylized world.',
    genre: 'Shooting',
    rating: 4.5,
    playersOnline: 19000,
    availability: 'Online',
    tags: ['Shooting', 'Multiplayer', 'PvP', 'Archery', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/narrow-one',
      approvedExternalUrl: 'https://www.crazygames.com/embed/narrow-one',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Archery PvP', accentStart: '#fbbf24', accentEnd: '#92400e' },
  },
  {
    id: 'cg-deadshot-io',
    name: 'Deadshot.io',
    url: 'https://www.crazygames.com/embed/deadshot-io',
    description:
      'Lightning-fast browser FPS: tight gunplay, ranked-style lobbies, weapon variety, and quick-match team deathmatch against live players.',
    genre: 'Shooting',
    rating: 4.6,
    playersOnline: 26000,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Multiplayer', 'PvP', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending', 'featured'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/deadshot-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/deadshot-io',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Browser FPS', accentStart: '#f87171', accentEnd: '#7f1d1d' },
  },
  {
    id: 'cg-subway-clash-3d',
    name: 'Subway Clash 3D',
    url: 'https://www.crazygames.com/embed/subway-clash-3d',
    description:
      'Team-based 3D shooter set across subway tunnels and city streets: capture points, heavy weapons, and live squad skirmishes.',
    genre: 'Shooting',
    rating: 4.4,
    playersOnline: 15000,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Multiplayer', 'PvP', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/subway-clash-3d',
      approvedExternalUrl: 'https://www.crazygames.com/embed/subway-clash-3d',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Squad Warfare', accentStart: '#38bdf8', accentEnd: '#0c4a6e' },
  },
  {
    id: 'cg-time-shooter-2',
    name: 'Time Shooter 2',
    url: 'https://www.crazygames.com/embed/time-shooter-2',
    description:
      'SUPERHOT-style tactical FPS: time moves only when you move, weapons shatter after a few shots, and every duel is a puzzle of angles.',
    genre: 'Shooting',
    rating: 4.5,
    playersOnline: 14000,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Tactical', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'staff-pick'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/time-shooter-2',
      approvedExternalUrl: 'https://www.crazygames.com/embed/time-shooter-2',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Time-Bending FPS', accentStart: '#e879f9', accentEnd: '#701a75' },
  },
  {
    id: 'cg-a-small-world-cup',
    name: 'A Small World Cup',
    url: 'https://www.crazygames.com/embed/a-small-world-cup',
    description:
      'Physics-driven one-on-one football: ragdoll strikers, comedy own-goals, and national-team knockout runs in quick two-minute matches.',
    genre: 'Sports',
    rating: 4.5,
    playersOnline: 17000,
    availability: 'Online',
    tags: ['Sports', 'Football', 'Physics', 'Multiplayer', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/a-small-world-cup',
      approvedExternalUrl: 'https://www.crazygames.com/embed/a-small-world-cup',
      embedMode: 'inline',
      controls: ['Keyboard', 'Touch'],
      modes: ['Solo', 'Local Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Ragdoll Football', accentStart: '#34d399', accentEnd: '#065f46' },
  },
  {
    id: 'cg-duck-life-4',
    name: 'Duck Life 4',
    url: 'https://www.crazygames.com/embed/ducklife-4',
    description:
      'The classic duck-training RPG: raise runners, flyers, and swimmers through mini-game tournaments across six biomes to become champion.',
    genre: 'Sports',
    rating: 4.6,
    playersOnline: 12000,
    availability: 'Online',
    tags: ['Sports', 'Racing', 'Training', 'RPG', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'staff-pick'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/ducklife-4',
      approvedExternalUrl: 'https://www.crazygames.com/embed/ducklife-4',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Training Champ', accentStart: '#facc15', accentEnd: '#854d0e' },
  },
  {
    id: 'cg-getaway-shootout',
    name: 'Getaway Shootout',
    url: 'https://www.crazygames.com/embed/getaway-shootout',
    description:
      'Two-player escape races: awkward hop movement, wild power-ups, and weapons across heist maps — first to the getaway vehicle wins.',
    genre: 'Action',
    rating: 4.5,
    playersOnline: 13000,
    availability: 'Online',
    tags: ['Action', 'Multiplayer', 'PvP', 'Party', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/getaway-shootout',
      approvedExternalUrl: 'https://www.crazygames.com/embed/getaway-shootout',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Heist Race', accentStart: '#fb923c', accentEnd: '#7c2d12' },
  },
  {
    id: 'cg-12-minibattles',
    name: '12 MiniBattles',
    url: 'https://www.crazygames.com/embed/12-minibattles',
    description:
      'The one-button party classic: 12 rapid-fire local versus minigames — tug of war, shootouts, and reaction duels on a single keyboard.',
    genre: 'Arcade',
    rating: 4.4,
    playersOnline: 11000,
    availability: 'Online',
    tags: ['Arcade', 'Party', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/12-minibattles',
      approvedExternalUrl: 'https://www.crazygames.com/embed/12-minibattles',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Party Pack', accentStart: '#c084fc', accentEnd: '#581c87' },
  },
  {
    id: 'cg-bad-ice-cream',
    name: 'Bad Ice-Cream',
    url: 'https://www.crazygames.com/embed/bad-ice-cream',
    description:
      'Nitrome arcade favorite: freeze ice walls, dodge roaming enemies, and collect every fruit across handcrafted puzzle mazes.',
    genre: 'Arcade',
    rating: 4.6,
    playersOnline: 10000,
    availability: 'Online',
    tags: ['Arcade', 'Puzzle', 'Nitrome', 'Multiplayer', 'CrazyGames'],
    badgeIds: ['modern', 'staff-pick'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/bad-ice-cream',
      approvedExternalUrl: 'https://www.crazygames.com/embed/bad-ice-cream',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Solo', 'Local Co-op'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Nitrome Classic', accentStart: '#67e8f9', accentEnd: '#155e75' },
  },
  {
    id: 'cg-bad-ice-cream-2',
    name: 'Bad Ice-Cream 2',
    url: 'https://www.crazygames.com/embed/bad-ice-cream-2',
    description:
      'The sequel sharpens everything: new enemies, trickier mazes, more fruit orders, and two-player co-op frosting chaos.',
    genre: 'Arcade',
    rating: 4.5,
    playersOnline: 9000,
    availability: 'Online',
    tags: ['Arcade', 'Puzzle', 'Nitrome', 'Multiplayer', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/bad-ice-cream-2',
      approvedExternalUrl: 'https://www.crazygames.com/embed/bad-ice-cream-2',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Solo', 'Local Co-op'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Nitrome Sequel', accentStart: '#67e8f9', accentEnd: '#155e75' },
  },
  {
    id: 'cg-worlds-hardest-game',
    name: "The World's Hardest Game",
    url: 'https://www.crazygames.com/embed/worlds-hardest-game',
    description:
      'The legendary precision challenge: dodge relentless blue balls with pixel-perfect timing and collect coins — deaths counted, pride optional.',
    genre: 'Arcade',
    rating: 4.3,
    playersOnline: 12000,
    availability: 'Online',
    tags: ['Arcade', 'Difficulty', 'Precision', 'Timing', 'CrazyGames'],
    badgeIds: ['modern', 'classic'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/worlds-hardest-game',
      approvedExternalUrl: 'https://www.crazygames.com/embed/worlds-hardest-game',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Precision Trial', accentStart: '#f87171', accentEnd: '#450a0a' },
  },
  {
    id: 'cg-murder',
    name: 'Murder',
    url: 'https://www.crazygames.com/embed/murder',
    description:
      'The social-betrayal cycle everyone knows: stab the king to take the throne, then spin and catch the next assassin before they strike.',
    genre: 'Casual',
    rating: 4.4,
    playersOnline: 8000,
    availability: 'Online',
    tags: ['Casual', 'Social', 'Timing', 'Stealth', 'CrazyGames'],
    badgeIds: ['modern'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/murder',
      approvedExternalUrl: 'https://www.crazygames.com/embed/murder',
      embedMode: 'inline',
      controls: ['Mouse'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Throne of Betrayal', accentStart: '#94a3b8', accentEnd: '#1e293b' },
  },
  {
    id: 'cg-mutilate-a-doll-2',
    name: 'Mutilate a Doll 2',
    url: 'https://www.crazygames.com/embed/mutilate-a-doll-2',
    description:
      'Physics sandbox with hundreds of weapons, hazards, and tools — build chaotic contraptions and let the ragdoll ragdoll.',
    genre: 'Casual',
    rating: 4.3,
    playersOnline: 9000,
    availability: 'Online',
    tags: ['Casual', 'Sandbox', 'Physics', 'Creative', 'CrazyGames'],
    badgeIds: ['modern'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/mutilate-a-doll-2',
      approvedExternalUrl: 'https://www.crazygames.com/embed/mutilate-a-doll-2',
      embedMode: 'inline',
      controls: ['Mouse'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Physics Sandbox', accentStart: '#a3e635', accentEnd: '#365314' },
  },
  {
    id: 'cg-knife-hit',
    name: 'Knife Hit',
    url: 'https://www.crazygames.com/embed/knife-hit',
    description:
      'Rhythm-based knife throwing: flick blades into the rotating log without clashing, break apples for bonuses, and face boss logs every fifth stage.',
    genre: 'Arcade',
    rating: 4.4,
    playersOnline: 8500,
    availability: 'Online',
    tags: ['Arcade', 'Timing', 'Precision', 'CrazyGames'],
    badgeIds: ['modern'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/knife-hit',
      approvedExternalUrl: 'https://www.crazygames.com/embed/knife-hit',
      embedMode: 'inline',
      controls: ['Mouse', 'Touch'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Blade Rhythm', accentStart: '#fda4af', accentEnd: '#881337' },
  },
  {
    id: 'cg-zombie-derby',
    name: 'Zombie Derby',
    url: 'https://www.crazygames.com/embed/zombie-derby',
    description:
      'Muscle cars versus the undead horde: nitro-fueled distance runs, mowing down walkers, and garage upgrades between apocalyptic sprints.',
    genre: 'Racing',
    rating: 4.3,
    playersOnline: 7500,
    availability: 'Online',
    tags: ['Racing', 'Zombies', 'Action', 'Upgrade', 'CrazyGames'],
    badgeIds: ['modern'],
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/zombie-derby',
      approvedExternalUrl: 'https://www.crazygames.com/embed/zombie-derby',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Undead Horsepower', accentStart: '#4ade80', accentEnd: '#14532d' },
  },

  // ── Multiplayer, co-op & 2-player wave — verified inline cabinets ──
  {
    id: 'cg-tank-trouble',
    name: 'Tank Trouble',
    url: 'https://www.crazygames.com/embed/tank-trouble',
    description:
      'The legendary 2-3 player couch duel: bouncing bullets, maze walls, and one-hit kills — outmaneuver friends in chaotic tank battles.',
    genre: 'Action',
    rating: 4.6,
    playersOnline: 16000,
    availability: 'Online',
    tags: ['Action', 'Multiplayer', 'PvP', 'Local', 'Party', 'CrazyGames'],
    badgeIds: ['modern', 'trending', 'featured'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/tank-trouble',
      approvedExternalUrl: 'https://www.crazygames.com/embed/tank-trouble',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Couch Duel', accentStart: '#4ade80', accentEnd: '#14532d' },
  },
  {
    id: 'cg-gun-mayhem-2',
    name: 'Gun Mayhem 2',
    url: 'https://www.crazygames.com/embed/gun-mayhem-2',
    description:
      'Explosive 2-4 player platform fighter: double jumps, wild weapon drops, and ring-outs across destructible arenas with friends on one keyboard.',
    genre: 'Action',
    rating: 4.6,
    playersOnline: 14000,
    availability: 'Online',
    tags: ['Action', 'Multiplayer', 'PvP', 'Local', 'Platformer', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/gun-mayhem-2',
      approvedExternalUrl: 'https://www.crazygames.com/embed/gun-mayhem-2',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Arena Brawler', accentStart: '#fb923c', accentEnd: '#7c2d12' },
  },
  {
    id: 'cg-bomb-it-7',
    name: 'Bomb It 7',
    url: 'https://www.crazygames.com/embed/bomb-it-7',
    description:
      'Bomberman-style blowouts for up to 4 players: trap rivals in blast corridors, grab power-ups, and rule the maze in local versus or co-op story mode.',
    genre: 'Arcade',
    rating: 4.5,
    playersOnline: 11000,
    availability: 'Online',
    tags: ['Arcade', 'Multiplayer', 'PvP', 'Local', 'Party', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/bomb-it-7',
      approvedExternalUrl: 'https://www.crazygames.com/embed/bomb-it-7',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Local Co-op'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Blast Party', accentStart: '#facc15', accentEnd: '#854d0e' },
  },
  {
    id: 'cg-soccer-physics',
    name: 'Soccer Physics',
    url: 'https://www.crazygames.com/embed/soccer-physics',
    description:
      'Two-player ragdoll football mayhem: flailing kicks, impossible headers, and hilarious own goals in lightning-fast one-button matches.',
    genre: 'Sports',
    rating: 4.4,
    playersOnline: 10000,
    availability: 'Online',
    tags: ['Sports', 'Football', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/soccer-physics',
      approvedExternalUrl: 'https://www.crazygames.com/embed/soccer-physics',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Ragdoll Kickoff', accentStart: '#34d399', accentEnd: '#065f46' },
  },
  {
    id: 'cg-basketbros',
    name: 'BasketBros',
    url: 'https://www.crazygames.com/embed/basketbros',
    description:
      'Two-player arcade hoops: ridiculous dunks, dirty blocks, and buzzer-beaters in fast one-on-one basketball duels on one keyboard.',
    genre: 'Sports',
    rating: 4.5,
    playersOnline: 9500,
    availability: 'Online',
    tags: ['Sports', 'Basketball', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/basketbros',
      approvedExternalUrl: 'https://www.crazygames.com/embed/basketbros',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Hoop Duel', accentStart: '#fb923c', accentEnd: '#9a3412' },
  },
  {
    id: 'cg-rooftop-snipers-2',
    name: 'Rooftop Snipers 2',
    url: 'https://www.crazygames.com/embed/rooftop-snipers-2',
    description:
      'The dueling sequel: wobble across rooftops, time your shots, and knock your rival off the ledge in tense two-player sniper showdowns.',
    genre: 'Shooting',
    rating: 4.5,
    playersOnline: 12000,
    availability: 'Online',
    tags: ['Shooting', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/rooftop-snipers-2',
      approvedExternalUrl: 'https://www.crazygames.com/embed/rooftop-snipers-2',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Rooftop Rivalry', accentStart: '#94a3b8', accentEnd: '#0f172a' },
  },
  {
    id: 'cg-money-movers',
    name: 'Money Movers',
    url: 'https://www.crazygames.com/embed/money-movers',
    description:
      'Two-player co-op heist platforming: swap between the brothers, trigger switches for each other, dodge guards, and smuggle the loot out together.',
    genre: 'Adventure',
    rating: 4.5,
    playersOnline: 9000,
    availability: 'Online',
    tags: ['Adventure', 'Puzzle', 'Platformer', 'Co-op', 'Multiplayer', 'CrazyGames'],
    badgeIds: ['modern', 'staff-pick'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/money-movers',
      approvedExternalUrl: 'https://www.crazygames.com/embed/money-movers',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Co-op', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Heist Duo', accentStart: '#4ade80', accentEnd: '#166534' },
  },
  {
    id: 'cg-wrestle-jump',
    name: 'Wrestle Jump',
    url: 'https://www.crazygames.com/embed/wrestle-jump',
    description:
      'Two-player wrestling flips: time your lunges, snap your opponent to the mat, and defend your crown in rapid-fire one-button bouts.',
    genre: 'Sports',
    rating: 4.4,
    playersOnline: 7000,
    availability: 'Online',
    tags: ['Sports', 'Fighting', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/wrestle-jump',
      approvedExternalUrl: 'https://www.crazygames.com/embed/wrestle-jump',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Ring Rumble', accentStart: '#f87171', accentEnd: '#7f1d1d' },
  },
  {
    id: 'cg-ping-pong-chaos',
    name: 'Ping Pong Chaos',
    url: 'https://www.crazygames.com/embed/ping-pong-chaos',
    description:
      'Two-player table tennis gone sideways: wobbling paddles, spin shots, and sudden-death rallies in frantic head-to-head matches.',
    genre: 'Sports',
    rating: 4.3,
    playersOnline: 6500,
    availability: 'Online',
    tags: ['Sports', 'Multiplayer', 'PvP', 'Local', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/ping-pong-chaos',
      approvedExternalUrl: 'https://www.crazygames.com/embed/ping-pong-chaos',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Versus', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Table Tennis Turmoil', accentStart: '#c084fc', accentEnd: '#581c87' },
  },
  {
    id: 'cg-bubble-trouble',
    name: 'Bubble Trouble',
    url: 'https://www.crazygames.com/embed/bubble-trouble',
    description:
      'The split-screen classic: pop bouncing bubbles into smaller fragments with harpoon shots — solo or two-player co-op survival.',
    genre: 'Arcade',
    rating: 4.4,
    playersOnline: 8500,
    availability: 'Online',
    tags: ['Arcade', 'Multiplayer', 'Co-op', 'Local', 'Classic', 'CrazyGames'],
    badgeIds: ['modern', 'classic'],
    multiplayerType: 'P2P',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/bubble-trouble',
      approvedExternalUrl: 'https://www.crazygames.com/embed/bubble-trouble',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Local Co-op', 'Solo'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Split-Screen Classic', accentStart: '#67e8f9', accentEnd: '#155e75' },
  },
  {
    id: 'cg-bonk-io',
    name: 'Bonk.io',
    url: 'https://www.crazygames.com/embed/bonkio',
    description:
      'Multiplayer physics arena: bump rivals off ledges, craft custom maps, and out-momentum opponents in last-circle-of-hell showdowns.',
    genre: 'Casual',
    rating: 4.5,
    playersOnline: 13000,
    availability: 'Online',
    tags: ['Casual', 'Multiplayer', 'PvP', 'Physics', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/bonkio',
      approvedExternalUrl: 'https://www.crazygames.com/embed/bonkio',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Physics Arena', accentStart: '#38bdf8', accentEnd: '#0c4a6e' },
  },
  {
    id: 'cg-territorial-io',
    name: 'Territorial.io',
    url: 'https://www.crazygames.com/embed/territorial-io',
    description:
      'Real-time strategy on a live world map: expand borders, forge and break alliances, and out-scale hundreds of simultaneous opponents.',
    genre: 'Strategy',
    rating: 4.4,
    playersOnline: 15000,
    availability: 'Online',
    tags: ['Strategy', 'Multiplayer', 'PvP', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/territorial-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/territorial-io',
      embedMode: 'inline',
      controls: ['Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Map Domination', accentStart: '#a3e635', accentEnd: '#365314' },
  },
  {
    id: 'cg-voxiom-io',
    name: 'Voxiom.io',
    url: 'https://www.crazygames.com/embed/voxiom-io',
    description:
      'Voxel battle royale: mine, build cover, swap weapons, and survive shrinking storms against a full lobby of live players.',
    genre: 'Shooting',
    rating: 4.4,
    playersOnline: 11000,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Multiplayer', 'PvP', 'Battle Royale', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/voxiom-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/voxiom-io',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Voxel Royale', accentStart: '#4ade80', accentEnd: '#14532d' },
  },
  {
    id: 'cg-madalin-cars-multiplayer',
    name: 'Madalin Cars Multiplayer',
    url: 'https://www.crazygames.com/embed/madalin-cars-multiplayer',
    description:
      'Open-world supercar playground with live lobbies: pick from dozens of hypercars, drift runways, and cruise or race friends in real time.',
    genre: 'Racing',
    rating: 4.6,
    playersOnline: 18000,
    availability: 'Online',
    tags: ['Racing', 'Multiplayer', 'Open World', 'Drifting', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending', 'featured'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/madalin-cars-multiplayer',
      approvedExternalUrl: 'https://www.crazygames.com/embed/madalin-cars-multiplayer',
      embedMode: 'inline',
      controls: ['Keyboard'],
      modes: ['Online Versus', 'Online Co-op'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Supercar Lobby', accentStart: '#f87171', accentEnd: '#450a0a' },
  },
  {
    id: 'cg-kart-wars',
    name: 'Kart Wars',
    url: 'https://www.crazygames.com/embed/kart-wars',
    description:
      'Multiplayer kart combat: rockets, shields, and drifting mayhem across arenas filled with live rival drivers.',
    genre: 'Racing',
    rating: 4.3,
    playersOnline: 8000,
    availability: 'Online',
    tags: ['Racing', 'Multiplayer', 'PvP', 'Combat', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/kart-wars',
      approvedExternalUrl: 'https://www.crazygames.com/embed/kart-wars',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Kart Combat', accentStart: '#fbbf24', accentEnd: '#92400e' },
  },
  {
    id: 'cg-winter-clash-3d',
    name: 'Winter Clash 3D',
    url: 'https://www.crazygames.com/embed/winter-clash-3d',
    description:
      'Team-based holiday shooter: Santa-armed squad battles, capture-point objectives, and snow-covered arenas against live teams.',
    genre: 'Shooting',
    rating: 4.4,
    playersOnline: 9000,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Multiplayer', 'PvP', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/winter-clash-3d',
      approvedExternalUrl: 'https://www.crazygames.com/embed/winter-clash-3d',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Snow Squad', accentStart: '#e0f2fe', accentEnd: '#0c4a6e' },
  },
  {
    id: 'cg-betrayal-io',
    name: 'Betrayal.io',
    url: 'https://www.crazygames.com/embed/betrayal-io',
    description:
      'Social deduction with live lobbies: complete tasks, spot the impostor, and survive betrayals in Among Us-style crew warfare.',
    genre: 'Casual',
    rating: 4.3,
    playersOnline: 8500,
    availability: 'Online',
    tags: ['Casual', 'Multiplayer', 'Social', 'Deduction', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/betrayal-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/betrayal-io',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Social Deduction', accentStart: '#f87171', accentEnd: '#1e293b' },
  },
  {
    id: 'cg-buildnow-gg',
    name: 'BuildNow GG',
    url: 'https://www.crazygames.com/embed/buildnow-gg',
    description:
      'Build-and-battle shooter: wall up, edit, and outgun rivals in third-person PvP inspired by battle-royale construction duels.',
    genre: 'Shooting',
    rating: 4.5,
    playersOnline: 13500,
    availability: 'Online',
    tags: ['Shooting', 'Multiplayer', 'PvP', 'Building', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/buildnow-gg',
      approvedExternalUrl: 'https://www.crazygames.com/embed/buildnow-gg',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Build & Battle', accentStart: '#c084fc', accentEnd: '#581c87' },
  },
  {
    id: 'cg-drednot-io',
    name: 'Drednot.io',
    url: 'https://www.crazygames.com/embed/drednot-io',
    description:
      'Multiplayer airship warfare: crew your flying fortress, load turrets, board enemies, and duel other ships in sky-high team battles.',
    genre: 'Action',
    rating: 4.4,
    playersOnline: 7000,
    availability: 'Online',
    tags: ['Action', 'Multiplayer', 'PvP', 'Teamwork', 'Modern', 'CrazyGames'],
    badgeIds: ['modern'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/drednot-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/drednot-io',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus', 'Online Co-op'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Airship Armada', accentStart: '#94a3b8', accentEnd: '#1e293b' },
  },
  {
    id: 'cg-kour-io',
    name: 'Kour.io',
    url: 'https://www.crazygames.com/embed/kour-io',
    description:
      'Slick browser FPS with ranked energy: crisp movement, weapon loadouts, and instant team deathmatch lobbies against live players.',
    genre: 'Shooting',
    rating: 4.5,
    playersOnline: 14500,
    availability: 'Online',
    tags: ['Shooting', 'FPS', 'Multiplayer', 'PvP', 'Modern', 'CrazyGames'],
    badgeIds: ['modern', 'trending', 'featured'],
    multiplayerType: 'Server',
    launchConfig: {
      approvedEmbedUrl: 'https://www.crazygames.com/embed/kour-io',
      approvedExternalUrl: 'https://www.crazygames.com/embed/kour-io',
      embedMode: 'inline',
      controls: ['Keyboard', 'Mouse'],
      modes: ['Online Versus'],
      trustNote:
        'CrazyGames first-party /embed/ endpoint verified 200 with no frame-blocking headers.',
    },
    art: { eyebrow: 'Lobby FPS', accentStart: '#fb923c', accentEnd: '#7c2d12' },
  },
];
